--List the number of films per category.
SELECT
    c.name AS category_name,
    COUNT(fc.film_id) AS number_of_films
FROM
    category c
JOIN
    film_category fc ON c.category_id = fc.category_id
GROUP BY
    c.name
ORDER BY
    number_of_films DESC;
--This is a great set of challenges to practice SQL joins and aggregation using the Sakila database. Here are the SQL queries for each task, including the necessary joins and grouping.

🤝 Challenge: Joining on Multiple Tables
1. List the number of films per category.
This requires joining category and film_category to link category names to films, and then using COUNT() and GROUP BY.

SQL

SELECT
    c.name AS category_name,
    COUNT(fc.film_id) AS number_of_films
FROM
    category c
JOIN
    film_category fc ON c.category_id = fc.category_id
GROUP BY
    c.name
ORDER BY
    number_of_films DESC;
--2. Retrieve the store ID, city, and country for each store.
SELECT
    s.store_id,
    ci.city,
    co.country
FROM
    store s
JOIN
    address a ON s.address_id = a.address_id
JOIN
    city ci ON a.city_id = ci.city_id
JOIN
    country co ON ci.country_id = co.country_id
ORDER BY
    s.store_id;
--Calculate the total revenue generated by each store in dollars.
SELECT
    s.store_id,
    SUM(p.amount) AS total_revenue
FROM
    store s
JOIN
    staff st ON s.store_id = st.store_id
JOIN
    payment p ON st.staff_id = p.staff_id
GROUP BY
    s.store_id
ORDER BY
    total_revenue DESC;
---Determine the average running time of films for each category.
SELECT
    c.name AS category_name,
    ROUND(AVG(f.length), 2) AS average_running_time_minutes
FROM
    category c
JOIN
    film_category fc ON c.category_id = fc.category_id
JOIN
    film f ON fc.film_id = f.film_id
GROUP BY
    c.name
ORDER BY
    average_running_time_minutes DESC;
--Identify the film categories with the longest average running time.
SELECT
    c.name AS category_name,
    ROUND(AVG(f.length), 2) AS average_running_time_minutes
FROM
    category c
JOIN
    film_category fc ON c.category_id = fc.category_id
JOIN
    film f ON fc.film_id = f.film_id
GROUP BY
    c.name
ORDER BY
    average_running_time_minutes DESC
LIMIT 1;
--Display the top 10 most frequently rented movies in descending order.
SELECT
    f.title,
    COUNT(r.rental_id) AS rental_count
FROM
    film f
JOIN
    inventory i ON f.film_id = i.film_id
JOIN
    rental r ON i.inventory_id = r.inventory_id
GROUP BY
    f.title
ORDER BY
    rental_count DESC
LIMIT 10;
--Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT
    f.title,
    s.store_id,
    COUNT(i.inventory_id) AS inventory_count
FROM
    film f
JOIN
    inventory i ON f.film_id = i.film_id
JOIN
    store s ON i.store_id = s.store_id
WHERE
    f.title = 'ACADEMY DINOSAUR' AND s.store_id = 1
GROUP BY
    f.title, s.store_id;

-- Interpretation: If the query returns a row with inventory_count > 0, it can be rented.
--Distinct film titles and their availability status in the inventory.
SELECT
    f.title,
    CASE
        WHEN i.inventory_id IS NOT NULL THEN 'Available'
        ELSE 'NOT available'
    END AS availability_status
FROM
    film f
LEFT JOIN
    inventory i ON f.film_id = i.film_id
GROUP BY
    f.title, availability_status  -- Group by both to ensure each title is listed once with its status
ORDER BY
    f.title;
